### ISSUE TITLE
Create new example

### ISSUE THREAD

**Issue by flyingsilverfin** [graknlabs/examples#118]
## Problem to Solve

To create a new example, we encompass a series of tasks:

1. Choose a domain of interest that also illustrates a good community example
2. Create a method of loading a dataset from the domain into TypeDB - we should use Bazel as the build system
3. Create an API or CLI/Visual example of usage of the dataset
4. Test the example using Factory
5. Write a blog

## Guidelines

A good example will take the creator 1-2 weeks to finish all the steps for, and cover learning everything from the TypeDB data model, to using a client, Bazel as a build system, and writing.

**Comment by james-whiteside** [comment]
This is now under primary responsibilities of the Product team and forms part of our larger documentation goals.
