### ISSUE TITLE
train network example is gone

### ISSUE THREAD

**Issue by brettforbes** [graknlabs/examples#138]
you used to have a train station example

this is your only set of example data with GPS coordinates

so if one wanted to test mapping for a visualisation system, it would be ideal to be able to replicate that old tkinter interface

yet this data is no longer available

where is it?

**Comment by dmitrii-ubskii** [comment]
The tube network example had, unfortunately, grown incompatible with TypeDB and was sunsetted.

The old tube network example can be obtained at [the preceding commit.](https://github.com/vaticle/typedb-examples/tree/26a42734d7cf5f60191871d549f6594f671d23cc/tube_network)

**Comment by brettforbes** [comment]
Thanks Dimitri for the quick response.

If we fixed it up, and made it useful for the community, do you want it back as an example??? Alternatively we could post it as the mapping example for our open source viz tool. What should we do if we fix the repo?

Thanks

**Comment by brettforbes** [comment]
hi @dmitrii-ubskii ,
I tried your link, but I am not sure how to download that repo. Sorry to ask a stupid question, but can you please explain how i can download that repo?

thanks

**Comment by dmitrii-ubskii** [comment]
> can you please explain how i can download that repo?

You would need to `git checkout 26a42734` in an already cloned working copy (i.e. `git clone https://github.com/vaticle/typedb-examples.git; cd typedb-examples; git checkout 26a42734`). You'd probably want to create a branch after you do that by running `git checkout -b <branch-name>`.

> If we fixed it up, and made it useful for the community, do you want it back as an example?

You're welcome to open a PR when you do, or you could submit it for [typedb-awesome](https://github.com/vaticle/typedb-awesome) if it's a larger project.

P.S. I should have linked #132 in my earlier comment, it has a bigger write up on why the example was removed. You may find it useful.

**Comment by dmitrii-ubskii** [comment]
The PR isn't really the place for such discussion, so I'll respond here. Reproduced for posterity:

> We would like to refurbish this example as a GIS mapping example, which we plan to do in [kepler.gl](https://kepler.gl/).
>
> Can you give us access to the repo?
>
> We will refurbish the loading code, but dump the analytics side, and focus on GIS visualisation. then we will publish the repo somewhere as open source, and we can add the analytics when you finally get that done

The conventional way to contribute is to fork the repository by clicking the button you should be able to see up at the top of the page. That creates a copy of the repository that you have full access to. When your contribution is ready, you can then create a pull request by navigating to the Pull requests tab of _this_ repository (https://github.com/vaticle/typedb-examples/pulls) and clicking the green "New pull request" button.

**Comment by brettforbes** [comment]
thanks @dmitrii-ubskii
