### ISSUE TITLE
Tutorial to migrate from MongoDB to TypeDB

### ISSUE THREAD

**Issue by grabl** [graknlabs/examples#14]
_This issue was originally posted by @sorsaffari  on 2018-08-22 19:16_.

The main objectives of this task are to:
1. Describe the strengths and weaknesses of MongoDB
2. Describe the strengths of TypeDB
3. Describe how to model a simple domain with rich relationships in TypeDB
4. Load the data into TypeDB (keep it short; refer to migration tutorial if the user wants to learn more)
5. Demonstrate interesting and insightful queries using TypeDB

## Database Comparison
**The audience is assumed to be experienced with MongoDB**

#### MongoDB is great in,
- Allows changes in the design over time
- Has built-in support for Geospatial data
- Scales well horizontally (Sharding)
- Document based query language that feels familiar to the JS community

#### MongoDB sucks in that it's:
- Limited by its initial design: it’s only when you start working with a complex aggregation framework, that you realise the need to redesign the data scheme
- The aggregation framework gets large fast and becomes difficult to read (mongoose tries to solve this).
- It’s not possible to bind logic to a stored procedure
(complex) transactions are sacrificed for better scalability
- Proper (strict) indexing is required for better performance. From MongoDB Docs

#### TypeDB is awesome in,
- You don’t have to know all future requirements when coming up with the initial design. as the requirements evolve, TypeDB adopts
- Queries are short and easy to read
- Rules can be defined to make my knowledge graph learn and become more intelligent
- Interconnected pieces of data, allow complex transactions

### Dataset and Analysis
**People** who **call** each other. Those who make calls have a **contract** with **company** Telecom.

#### Insights
- Since September 14th, which customers called person X?
- Who are the people who have received a call from a London customer aged over 50 who has previously called someone aged under 20?
- Who are the common contacts of customers X and Y?
- Who are the customers who 1) have all called each other and 2) have all called person X at least once?
- How does the average call duration among customers aged under 20 compare those aged over 40?

**Comment by james-whiteside** [comment]
This will come under the broader Migration section in the new documentation.
