### ISSUE TITLE
Files missing in test data

### ISSUE THREAD

**Issue by NihadAbouzid** [graknlabs/examples#140]
I think the test data folder of biology catalogue_of_life is missing some files used at the following locations of the config.json

https://github.com/vaticle/typedb-examples/blob/2dec7a8e8443d73f1d86672bc9674502bf268c91/biology/catalogue_of_life/loader-config.json.template#L74
https://github.com/vaticle/typedb-examples/blob/2dec7a8e8443d73f1d86672bc9674502bf268c91/biology/catalogue_of_life/loader-config.json.template#L164
https://github.com/vaticle/typedb-examples/blob/2dec7a8e8443d73f1d86672bc9674502bf268c91/biology/catalogue_of_life/loader-config.json.template#L230
https://github.com/vaticle/typedb-examples/blob/2dec7a8e8443d73f1d86672bc9674502bf268c91/biology/catalogue_of_life/loader-config.json.template#L266
https://github.com/vaticle/typedb-examples/blob/2dec7a8e8443d73f1d86672bc9674502bf268c91/biology/catalogue_of_life/loader-config.json.template#L308

I removed the sections in the config causing problems leaving only the parenthood relation that I can successfully import.

**Comment by alexjpwalker** [comment]
@dmitrii-ubskii Do you know why (some of) the files in `loader-config.json.template` don't exist in the repo? Looking at the test data, for example we have `VernacularName.tsv`, but the JSON data is looking for `VernacularNameWithID.tsv`.

**Comment by dmitrii-ubskii** [comment]
Those files are prepared by `Loader.prepareData()` which gets called in `loadTestData()` before all tests. In particular, data preparation gives a unique ID t oeach vernacular name and separates the different kinds of regions into their own files.
