### ISSUE TITLE
move the scattered (old) examples in one single repository

### ISSUE THREAD

**Issue by grabl** [graknlabs/examples#30]
_This issue was originally posted by @sorsaffari  on 2018-09-17 19:57_.

**move to archived:**
instructions: [move while retaining the commit history](https://gist.github.com/sorsaffari/f2c4e3bc5134a576e88cb05915bcda22)
- [x] https://github.com/graknlabs/sample-datasets
- [x] https://github.com/graknlabs/sample-projects
- [x] https://github.com/graknlabs/biomed
- [x] https://github.com/graknlabs/grakn-movie-recommender  > retrieve the data > wait for Nick's (the author) response
- [x] https://github.com/graknlabs/horn-clause-mining
- [x] https://github.com/graknlabs/amazon

**Comment by sorsaffari** [comment]
@haikalpribadi I need push access to [horn-clause-mining](https://github.com/graknlabs/horn-clause-mining)

**Comment by haikalpribadi** [comment]
done @sorsaffari

**Comment by sorsaffari** [comment]
@haikalpribadi need write access to [grakn-movie-recommender](https://github.com/graknlabs/grakn-movie-recommender) as well.

**Comment by haikalpribadi** [comment]
done @sorsaffari !
