### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/examples#39]
It's good practice to include the apache license for each single example.

**Comment by alexjpwalker** [comment]
We need:

- [ ] The correct license header (Apache - see typedb-client-java for reference) at the top of every file (except for binary file types such as images);
- [ ] A `checkstyle_test` Bazel rule placed in every BUILD file to achieve full coverage of the repository;
- [ ] In CI, run `@vaticle_dependencies//tool/checkstyle:test-coverage` and test `$(bazel query 'kind(checkstyle_test, //...)')`.

This change would bring `typedb-examples` in line with our other repositories.
